name: model-deployment
run-name: ${{ github.actor }} is submitting model deployment job

on: workflow_dispatch

env:
  ROLE: ${{ secrets.ROLE }}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.15"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ".python-version"
          architecture: 'x64'

      - name: Install the project
        run: uv sync --locked --all-extras

      - name: Run tests
        run: uv run pytest -v tests

      - name: Configure AWS Credentials
        id: aws_creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run deployment pipeline
        run: e2e deploy --serverless
